language: node_js
node_js:
  - "8"

script:
  - git pull --tags
  - npm run build
  - npm run test
  - mv .travis.gitignore .gitignore

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: change
